CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR(120)                            NOT NULL,
    description        VARCHAR(7000)                           NOT NULL,
    annotation         VARCHAR(2000)                           NOT NULL,
    category_id        BIGINT                                  NOT NULL,
    event_date         TIMESTAMP without time zone             NOT NULL,
    location_lat       FLOAT4                                  NOT NULL,
    location_lon       FLOAT4                                  NOT NULL,
    paid               BOOLEAN                                 NOT NULL,
    participant_limit  INT                                     NOT NULL,
    request_moderation BOOLEAN                                 NOT NULL,
    confirmed_requests INT                                     NOT NULL,
    initiator_id       BIGINT                                  NOT NULL,
    created_on         TIMESTAMP without time zone             NOT NULL,
    published_on       TIMESTAMP without time zone             NOT NULL,
    state              VARCHAR(50)                             NOT NULL,
    views              BIGINT                                  NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT FK_EVENT_CATEGORY_ID FOREIGN KEY (category_id) references categories (id),
    CONSTRAINT FK_EVENT_INITIATOR_ID FOREIGN KEY (initiator_id) references users (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id     BIGINT                                  NOT NULL,
    requester_id BIGINT                                  NOT NULL,
    status       VARCHAR(50)                             NOT NULL,
    created_on   TIMESTAMP without time zone             NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT FK_REQUEST_EVENT_ID FOREIGN KEY (event_id) references events (id),
    CONSTRAINT FK_REQUEST_REQUESTER_ID FOREIGN KEY (requester_id) references users (id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(120)                            NOT NULL,
    pinned BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events_compilations
(
    event_id       BIGINT NOT NULL,
    compilation_id BIGINT NOT NULL,
    CONSTRAINT fk_events_compilations_event_id FOREIGN KEY (event_id) references events (id),
    CONSTRAINT fk_events_compilations_compilation_id FOREIGN KEY (compilation_id) references compilations (id)
);